name: Kaggle Login
description: "Login to Kaggle"
author: osbm
branding:
  icon: upload-cloud
  color: blue

inputs:
  kaggle_username:
    description:
      "The kaggle username"
    required: true
    default: ""

  kaggle_key:
    description:
      "The kaggle access API token to learn more visit https://github.com/Kaggle/kaggle-api#api-credentials "
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install kaggle
      shell: bash
      run: |
        pip install kaggle

    - name: Authenticate to Kaggle
      shell: bash
      run: |
        echo '{
          "username": "${{ inputs.kaggle_username }}",
          "key": "${{ inputs.kaggle_key }}"
        }' > kaggle.json
        mv kaggle.json ~/.kaggle/
        echo "Kaggle login successful"